#include "gpu/backend/RendererGPU.h"
#include "gpu/upload/SceneUploader.h"
#include "gpu/pipeline/VisibilityPipeline.h"
#include "graphics/Shader.h"
#include "core/ShaderLoader.h"

#include <iostream>

#include "gpu/commands/IndirectCommandBuffer.h"

void RendererGPU::init()
{
    normalShader  = ShaderLoader::loadPass("basic.vert", "basic.frag");
    computeShader = ShaderLoader::loadCompute("cull.comp");
    debugShader   = ShaderLoader::loadDebug("indirect_debug.vert", "indirect_debug.frag");

    std::cout << "RendererGPU init\n";
}

void RendererGPU::render(
    SceneUploader& scene,
    VisibilityPipeline& visibility,
    GLuint vao)
{
    std::cout << "RendererGPU render\n";
    scene.bindAll();
    visibility.bindOutputs(scene);

    glBindVertexArray(vao);

    glBindBuffer(GL_DRAW_INDIRECT_BUFFER,
                 scene.getDrawBuffer().getID());
                 
    // glBindBuffer(GL_PARAMETER_BUFFER,
    //              visibility.getCounterBuffer());4.6

    normalShader.use();

    // 1. GPU → CPU sync（counter）
    // glMemoryBarrier(GL_BUFFER_UPDATE_BARRIER_BIT |
    //                 GL_SHADER_STORAGE_BARRIER_BIT);

    // GLuint count = 0;

    // glBindBuffer(GL_SHADER_STORAGE_BUFFER,
    //              visibility.getCounterBuffer());
    // glGetBufferSubData(GL_SHADER_STORAGE_BUFFER,
    //                     0, 
    //                     sizeof(GLuint),
    //                     &count);
                        
    // std::cout << "visible count = " << count << std::endl;
    // if (count == 0)
    // {
    //     glBindVertexArray(0);
    //     return;
    // }

    // 2. draw
    glMemoryBarrier(
        GL_SHADER_STORAGE_BARRIER_BIT |
        GL_COMMAND_BARRIER_BIT
    );

    // glMultiDrawElementsIndirectCount(
    //     GL_TRIANGLES,
    //     GL_UNSIGNED_INT,
    //     nullptr,
    //     0,
    //     MAX_MESHES,
    //     0
    // );4.6

    glMultiDrawElementsIndirect(
        GL_TRIANGLES,
        GL_UNSIGNED_INT,
        nullptr,
        1024,
        0
    );

    // std::cout << "draw count = " << count << std::endl;

    glBindVertexArray(0);
}

void RendererGPU::render(
    SceneUploader& scene,
    VisibilityPipeline& visibility)
{
    std::cout << "[RendererGPU] render frame\n";

    // ------------------------------------------------------------
    // 1. Bind ALL GPU buffers (no VAO dependency)
    scene.bindAll();

    // Visibility pass must output:
    // - DrawIndirectBuffer (indirect commands)
    // - Visibility counter (optional)
    visibility.bindOutputs(scene);

    // ------------------------------------------------------------
    // 2. Run visibility / culling pipeline (compute shader stage)
    visibility.dispatch(scene, 9);

    // Memory barrier: ensure compute writes visible to draw stage
    glMemoryBarrier(
        GL_SHADER_STORAGE_BARRIER_BIT |
        GL_COMMAND_BARRIER_BIT
    );

    // ------------------------------------------------------------
    // 3. Bind indirect draw buffer
    const GLuint drawBuffer =
        scene.getDrawBuffer().getID();

    glBindBuffer(GL_DRAW_INDIRECT_BUFFER, drawBuffer);


    IndirectCommandBuffer cmd;
glGetBufferSubData(GL_DRAW_INDIRECT_BUFFER, 0, sizeof(cmd), &cmd);

std::cout << cmd.count << std::endl;


    // ------------------------------------------------------------
    // 4. Bind pipeline shader (vertex/fragment)
    normalShader.use();

    // ------------------------------------------------------------
    // 5. OPTIONAL: debug / visibility readback (disabled in prod)
    GLuint visibleCount = 0;
    glBindBuffer(GL_SHADER_STORAGE_BUFFER,
                 visibility.getCounterBuffer());

    glGetBufferSubData(GL_SHADER_STORAGE_BUFFER,
                        0,
                        sizeof(GLuint),
                        &visibleCount);

    std::cout << "visible count = " << visibleCount << "\n";

    if (visibleCount == 0)
        return;

    // ------------------------------------------------------------
    // 6. PURE GPU indirect draw
   
    // NOTE:
    // - No VAO
    // - Assumes vertex fetch from SSBO or global vertex buffer
    // - Draw commands generated by compute shader

    glMultiDrawElementsIndirect(
        GL_TRIANGLES,
        GL_UNSIGNED_INT,
        nullptr,
        visibleCount,   // max draws (can be replaced later by GPU counter)
        0
    );
}

void RendererGPU::drawIndirect(
    GLuint vao,
    int drawCount)
{
    glBindVertexArray(vao);

    glMultiDrawElementsIndirect(
        GL_TRIANGLES,
        GL_UNSIGNED_INT,
        nullptr,
        drawCount,
        0);

    glBindVertexArray(0);
}

void RendererGPU::drawIndirect(int drawCount)
{
    std::cout << "[RendererGPU] drawIndirect legacy call\n";

    glMultiDrawElementsIndirect(
        GL_TRIANGLES,
        GL_UNSIGNED_INT,
        nullptr,
        drawCount,
        0
    );
}

void RendererGPU::drawIndirectDebug(
    GLuint vao,
    VisibilityPipeline& visibility,
    Shader& debugShader)
{
    // debugShader.use();

    // glBindBuffer(GL_DRAW_INDIRECT_BUFFER,
    //              scene.getDrawBuffer().getID());

    // glBindVertexArray(vao);

    // glMultiDrawElementsIndirect(
    //     GL_TRIANGLES,
    //     GL_UNSIGNED_INT,
    //     nullptr,
    //     MAX_MESHES,
    //     0);

    // glBindVertexArray(0);
}