#version 430 core

layout(local_size_x = 64) in;

// =========================
// STRUCT

struct DrawElementsIndirectCommandBuffer
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

// =========================
// BUFFERS

layout(std430, binding = 4) buffer DrawBuffer
{
    DrawElementsIndirectCommandBuffer commands[];
};

layout(std430, binding = 6) buffer CounterBuffer
{
    uint drawCount;
    uint instanceCount;
} counter;

layout(std430, binding = 8) buffer VisibilityBuffer
{
    uint instanceIndices[];
};

void main()
{
    uint id = gl_GlobalInvocationID.x;

    // IMPORTANT: only generate valid draws
    if (id >= counter.drawCount)
        return;

    uint instanceID = instanceIndices[id];

    commands[id].count         = 36;
    commands[id].instanceCount = 1;
    commands[id].firstIndex    = 0;
    commands[id].baseVertex    = 0;
    commands[id].baseInstance  = instanceID;
}

