#version 430 core

layout(local_size_x = 64) in;

struct DrawCommand
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

layout(std430, binding = 4) buffer DrawBuffer
{
    DrawCommand commands[];
};

layout(std430, binding = 6) buffer CounterBuffer
{
    uint drawCount;
    uint instanceCount;
} counter;

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id >= counter.instanceCount)
        return;

    uint drawID = atomicAdd(counter.drawCount, 1u);

    commands[drawID].count = 36;
    commands[drawID].instanceCount = 1;
    commands[drawID].firstIndex = 0;
    commands[drawID].baseVertex = 0;
    commands[drawID].baseInstance = id;
}

