#version 430 core

layout(local_size_x = 64) in;

struct IndirectCommandBuffer
{
    uint count;
    uint instanceCount;
    uint firstIndex;
    uint baseVertex;
    uint baseInstance;
};

struct Instance
{
    uint transformID;
    uint meshID;
    uint materialID;
    uint visibilityID;
};

layout(std430, binding = 0) buffer ObjectBuffer
{    Instance objects[];   };

layout(std430, binding = 1) buffer TransformBuffer
{    mat4 transforms[];    };

layout(std430, binding = 2) buffer MeshBoundsBuffer
{    vec4 boundingSpheres[];    };

layout(std430, binding = 3) buffer InstanceBuffer
{    Instance instances[];    };

layout(std430, binding = 4) buffer DrawBuffer
{    IndirectCommandBuffer commands[];    };

layout(std430, binding = 6) buffer CounterBuffer
{    uint drawCount;    }counter;

layout(std430, binding = 7) buffer DebugBuffer
{    vec4 debugColor[];     };// per instance

layout(std430, binding = 8) buffer VisibilityBuffer
{    Instance visibleObjects[];    };

uniform mat4 viewProj;

bool sphereInFrustum(vec4 sphere, mat4 mvp)
{
    // world space center
    vec4 center = vec4(sphere.xyz, 1.0);

    vec4 clip = mvp * center;

    float w = clip.w;

    // simple clip-space test
    return (clip.x > -w - sphere.w &&
            clip.x <  w + sphere.w &&
            clip.y > -w - sphere.w &&
            clip.y <  w + sphere.w &&
            clip.z > -w - sphere.w &&
            clip.z <  w + sphere.w);
}

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id == 0)
        counter.drawCount = 0;

    memoryBarrierBuffer();

    if (id >= objects.length())
        return;

    uint drawID = atomicAdd(counter.drawCount, 1);

    commands[drawID].count = 36;
    commands[drawID].instanceCount = 1;
    commands[drawID].firstIndex = 0;
    commands[drawID].baseVertex = 0;
    commands[drawID].baseInstance = id;
}

#if 0
void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id == 0)
        counter.drawCount = 9;

    commands[id].count = 36;
    commands[id].instanceCount = 1;
    commands[id].firstIndex = 0;
    commands[id].baseVertex = 0;
    commands[id].baseInstance = id;
}
#endif
