#version 430 core

layout(local_size_x = 64) in;

// =========================
// DATA STRUCTS

struct Instance
{
    uint transformID;
    uint meshID;
    uint materialID;
    uint visibilityID;
};

// =========================
// BUFFERS

layout(std430, binding = 3) buffer InstanceBuffer
{
    Instance instances[];
};

layout(std430, binding = 2) buffer MeshBoundsBuffer
{
    vec4 boundingSpheres[];
};

layout(std430, binding = 6) buffer CounterBuffer
{
    uint drawCount;
    uint instanceCount;
} counter;

layout(std430, binding = 8) buffer VisibilityBuffer
{
    uint instanceIndices[];
};

// =========================
// CAMERA

layout(std140, binding = 0) uniform CameraUBO
{
    mat4 view;
    mat4 projection;
    vec4 viewPos;
};

// =========================

bool visibleTest(vec4 sphere, mat4 vp)
{
    vec4 c = vp * vec4(sphere.xyz, 1.0);
    float w = c.w;

    return (c.x > -w - sphere.w &&
            c.x <  w + sphere.w &&
            c.y > -w - sphere.w &&
            c.y <  w + sphere.w &&
            c.z > -w - sphere.w &&
            c.z <  w + sphere.w);
}

void main()
{
    uint id = gl_GlobalInvocationID.x;

    if (id >= counter.instanceCount)
        return;

    Instance inst = instances[id];

    uint meshID = inst.meshID;
    if (meshID >= boundingSpheres.length())
        return;

    mat4 vp = projection * view;

    vec4 sphere = boundingSpheres[meshID];

    if (!visibleTest(sphere, vp))
        return;

    uint visibleID = atomicAdd(counter.drawCount, 1u);

    instanceIndices[visibleID] = id;
}

